export const MAIN_ROUTE = "/"
export const PROFILE_ROUTE = "/profile"
export const WORKOUTS_ROUTE = "/workouts"
export const WORKOUT_ROUTE = "/workout"
export const ACTIVE_WORKOUT_ROUTE = "/active-workout"
export const CREATE_WORKOUT_ROUTE = "/create-workout"
